// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDoorStyle(arg1) {
  return window['go']['main']['App']['CreateDoorStyle'](arg1);
}

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function DeleteDoorStyle(arg1) {
  return window['go']['main']['App']['DeleteDoorStyle'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function ExportAllData() {
  return window['go']['main']['App']['ExportAllData']();
}

export function ExportAllDataToFile() {
  return window['go']['main']['App']['ExportAllDataToFile']();
}

export function ExportCatalogData() {
  return window['go']['main']['App']['ExportCatalogData']();
}

export function ExportCatalogDataToFile() {
  return window['go']['main']['App']['ExportCatalogDataToFile']();
}

export function ExportOverlayData() {
  return window['go']['main']['App']['ExportOverlayData']();
}

export function ExportOverlayDataToFile() {
  return window['go']['main']['App']['ExportOverlayDataToFile']();
}

export function GenerateCutList(arg1) {
  return window['go']['main']['App']['GenerateCutList'](arg1);
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobsPage(arg1) {
  return window['go']['main']['App']['GetJobsPage'](arg1);
}

export function GetOverlayCategories() {
  return window['go']['main']['App']['GetOverlayCategories']();
}

export function GetOverlayPresets() {
  return window['go']['main']['App']['GetOverlayPresets']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportAllData(arg1) {
  return window['go']['main']['App']['ImportAllData'](arg1);
}

export function ImportCatalogData(arg1) {
  return window['go']['main']['App']['ImportCatalogData'](arg1);
}

export function ImportOverlayData(arg1) {
  return window['go']['main']['App']['ImportOverlayData'](arg1);
}

export function LoadDoorStyles() {
  return window['go']['main']['App']['LoadDoorStyles']();
}

export function LoadJobs() {
  return window['go']['main']['App']['LoadJobs']();
}

export function SaveDoorStyleOrder(arg1) {
  return window['go']['main']['App']['SaveDoorStyleOrder'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['main']['App']['SaveJob'](arg1);
}

export function SaveOverlayCategories(arg1) {
  return window['go']['main']['App']['SaveOverlayCategories'](arg1);
}

export function SaveOverlayPresets(arg1) {
  return window['go']['main']['App']['SaveOverlayPresets'](arg1);
}

export function SearchGlobal(arg1) {
  return window['go']['main']['App']['SearchGlobal'](arg1);
}

export function UpdateDoorStyle(arg1, arg2) {
  return window['go']['main']['App']['UpdateDoorStyle'](arg1, arg2);
}

export function UpdateJob(arg1, arg2) {
  return window['go']['main']['App']['UpdateJob'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WipeAllData() {
  return window['go']['main']['App']['WipeAllData']();
}
