// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDoorStyle(arg1:main.DoorStyleRequest):Promise<main.DoorStyle>;

export function CreateJob(arg1:main.CreateJobRequest):Promise<main.Job>;

export function DeleteDoorStyle(arg1:string):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function GenerateCutList(arg1:string):Promise<main.CutListResponse>;

export function GetDrawerFrontCategories():Promise<Array<main.OverlayCategory>>;

export function GetJob(arg1:string):Promise<main.Job>;

export function GetJobsPage(arg1:main.JobPageRequest):Promise<main.JobPageResponse>;

export function GetOverlayCategories():Promise<Array<main.OverlayCategory>>;

export function GetOverlayPresets():Promise<Array<main.OverlayPreset>>;

export function GetSettings():Promise<main.AppSettings>;

export function LoadDoorStyles():Promise<Array<main.DoorStyle>>;

export function LoadJobs():Promise<Array<main.Job>>;

export function SaveDrawerFrontCategories(arg1:Array<main.OverlayCategory>):Promise<Array<main.OverlayCategory>>;

export function SaveJob(arg1:main.Job):Promise<main.Job>;

export function SaveOverlayCategories(arg1:Array<main.OverlayCategory>):Promise<Array<main.OverlayCategory>>;

export function SaveOverlayPresets(arg1:Array<main.OverlayPreset>):Promise<Array<main.OverlayPreset>>;

export function SearchGlobal(arg1:string):Promise<Array<main.GlobalSearchResult>>;

export function UpdateDoorStyle(arg1:string,arg2:main.DoorStyleRequest):Promise<main.DoorStyle>;

export function UpdateJob(arg1:string,arg2:main.UpdateJobRequest):Promise<main.Job>;

export function UpdateSettings(arg1:main.UpdateSettingsRequest):Promise<main.AppSettings>;
